### ISSUE TITLE
Allow replacement of parts of path names instead of renaming

### ISSUE THREAD

**Issue by nexinto-gmbh** [maxdome/swagger-combine#16]
In the current implementation paths would be renamed only if they match via ===.

I need a functionality to rename all paths of a schema. Its like replaceing the basepath on pathlevel with an regular expression like 
`'/\/api\/(.)*/' : '/api/moduleX/$1'`

I have different option to enhance your code and will ask you, what you prefer:

1. add an separate replace option for paths to differ between renaming and replacing.
```
"paths": {
        "rename": {
          "/pet/{petId}": "/pet/alive/{petId}"
        },
        "replace": {
          "/\/pet\/(.)*": "/pet/alive/$1"
        }
      }
```

2. allow regex expression as keys on the renaming path
```
"paths": {
        "rename": {
          "/pet/{petId}": "/pet/alive/{petId}",
          "/\/pet\/(.)*/": "/pet/alive/$1"
        },
      }
```

3. ??? other ideas

I will add the code and also the tests if you agree with this enhancement.

Thx

**Comment by fabsrc** [comment]
This would be a great enhancement. Still I'm not quite sure about your suggested solutions.

In 1. there would be two different option keys for the same functionality (renaming a path name) which might be confusing.
In 2. it might be hard to distinguish if the content of the key string is a regular expression or just a normal string, since paths tend to start and end with "/" like regular expressions.
As a third option I would propose to allow using a custom function for renaming paths, e.g.:

```js
{
  paths: {
    rename: function(pathname) {
      return pathname.replace(/\/pet\/(.)*/, '/pet/alive/$1');
    }
  }
}
```

This would of course only be possible using a `.js` configuration file but would also provide more flexibility.

Another solution would be to explicitly indicate that the renaming should be done using a regular expression, maybe like this:

```json
{
  "paths": {
    "rename": {
      "$regexp": {
        "/\/pet\/(.)*/": "/pet/alive/$1"
      }
    }
  }
}
```

**Comment by nexinto-gmbh** [comment]
#17
